/** Amharic display names for region & woreda select values (keys match regon_n_woreda.ts). */
export const REGION_LABELS_AM: Record<string, string> = {
  addis_ababa: 'አዲስ አበባ',
  afar: 'አፋር',
  amhara: 'አምራ',
  benishangul_gumuz: 'ቤንሻንጉል-ጉሙዝ',
  dire_dawa: 'ድሬ ዳዋ',
  gambela: 'ጋምቤላ',
  harari: 'ሐረር',
  oromia: 'ኦሮሚያ',
  sidama: 'ሲዳማ',
  somali: 'ሶማሌ',
  south_ethiopia: 'ደቡብ ኢትዮጵያ ክልል',
  south_west: 'ደቡብ ምዕራብ ኢትዮጵያ ሕዝቦች ክልል',
  tigray: 'ትግራይ',
};

export const WOREDA_LABELS_AM: Record<string, string> = {
  addis_ketema: 'አዲስ ከተማ',
  akaki_kality: 'አቃቂ ቃሊቲ',
  arada: 'አራዳ',
  bole: 'ቦሌ',
  gulele: 'ጉለሌ',
  kirkos: 'ቂርቆስ',
  kolfe_keranio: 'ኮልፌ ቀራኒዮ',
  lideta: 'ልደታ',
  nefas_silk: 'ነፋስ ስልክ-ላፍቶ',
  yeka: 'የካ',
  semera: 'ሰመራ',
  asayita: 'አሳይታ',
  awash: 'አዋሽ',
  dubti: 'ዱብቲ',
  erbti: 'ኤረብቲ',
  mile: 'ሚሌ',
  bahir_dar: 'ባሕር ዳር',
  gondar: 'ጎንደር',
  dessie: 'ደሴ',
  debre_markos: 'ደብረ ማርቆስ',
  debre_birhan: 'ደብረ ብርሃን',
  weldiya: 'ወልድያ',
  kombolcha: 'ኮምቦልቻ',
  finote_selam: 'ፍኖተ ሰላም',
  asosa: 'አሶሳ',
  bambasi: 'ባምባሲ',
  menge: 'መንገ',
  kemashi: 'ከማሽ',
  sherkole: 'ሸርኮል',
  dire_dawa_city: 'ድሬ ዳዋ',
  gurgura: 'ጉርጉራ',
  shinile: 'ሽኒሌ',
  gambela_town: 'ጋምቤላ',
  itang: 'ኢታንግ',
  abobo: 'አቦቦ',
  gog: 'ጎግ',
  jor: 'ጆር',
  harar: 'ሐረር',
  dire_teyara: 'ድሬ ተያራ',
  amir_nur: 'አሚር ኑር',
  adama: 'አዳማ',
  jimma: 'ጅማ',
  bishoftu: 'ቢሾፍቱ',
  shashamane: 'ሻሸመኔ',
  ambo: 'አምቦ',
  nekemte: 'ነቀምት',
  bale_robe: 'ባሌ ሮቤ',
  assela: 'አሰላ',
  adaa: 'አዳ',
  bako_tibe: 'ባኮ ቲቤ',
  batu: 'ባቱ',
  hawassa: 'ሐዋሳ',
  yirgalem: 'ይርጋለም',
  aleta_wondo: 'አለታ ወንዶ',
  bensa: 'ቤንሳ',
  chuko: 'ቹኮ',
  jijiga: 'ጅጅጋ',
  gode: 'ጎዴ',
  kelafo: 'ኬላፎ',
  degehabur: 'ደገሀቡር',
  warder: 'ዋርደር',
  arba_minch: 'አርባ ምንጭ',
  sodo: 'ሶዶ',
  dilla: 'ድላ',
  hossana: 'ሆሳኝ',
  wolaita_sodo: 'ወላይታ ሶዶ',
  jinka: 'ጅንካ',
  bonga: 'ቦንጋ',
  mizan_aman: 'ምዛን አማን',
  tepi: 'ተፒ',
  bench_maji: 'ቤንች ማጂ',
  maji: 'ማጂ',
  mekelle: 'መቀሌ',
  adigrat: 'አዲግራት',
  axum: 'አክሱም',
  shire: 'ሺሬ',
  adwa: 'አድዋ',
  humera: 'ሁመራ',
};
